[project]
name = "corrosionmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "classiq>=0.80.1",
    "ipykernel>=6.29.5",
    "openfermion>=1.7.0",
    "pyscf>=2.9.0",
]
